name: "Deploy"
run-name: "Deploy by @${{ github.actor }}"

on:
  workflow_dispatch:

permissions:
  id-token: write
  checks: write
  contents: read

jobs:
  upload-index-and-css:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-duration-seconds: 900
          mask-aws-account-id: false
          role-session-name: github-actions
      - run: aws s3 cp ./front-end/index.html s3://colinvitkus.com
      - run: aws s3 cp ./front-end/styles.css s3://colinvitkus.com
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
